"""initial models

Revision ID: ef3645cbc8c8
Revises: 
Create Date: 2025-08-10 02:38:49.881878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3645cbc8c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_ticker'), 'assets', ['ticker'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='client_status'), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.CheckConstraint('buy_price > 0', name='ck_allocations_buy_price_pos'),
    sa.CheckConstraint('quantity > 0', name='ck_allocations_quantity_pos'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_allocations_asset_id', 'allocations', ['asset_id'], unique=False)
    op.create_index('ix_allocations_client_id', 'allocations', ['client_id'], unique=False)
    op.create_table('daily_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_daily_returns_asset_date')
    )
    op.create_index('ix_daily_returns_asset_id', 'daily_returns', ['asset_id'], unique=False)
    op.create_index('ix_daily_returns_date', 'daily_returns', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_returns_date', table_name='daily_returns')
    op.drop_index('ix_daily_returns_asset_id', table_name='daily_returns')
    op.drop_table('daily_returns')
    op.drop_index('ix_allocations_client_id', table_name='allocations')
    op.drop_index('ix_allocations_asset_id', table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_assets_ticker'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
